# Generated by Django 3.0.8 on 2022-05-21 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220521_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='End_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 16, 38, 6, 568705), null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 16, 38, 6, 568705), null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='End_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 16, 38, 6, 568705), null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 16, 38, 6, 568705), null=True),
        ),
    ]
