# Generated by Django 3.0.8 on 2022-05-21 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220521_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Days',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='End_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Start_date',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='End_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 16, 46, 57, 200277), null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 16, 46, 57, 200277), null=True),
        ),
    ]
