# Generated by Django 3.0.8 on 2022-05-21 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220521_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='End_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 5, 21, 19, 19, 52, 407187), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Start_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 5, 21, 19, 19, 52, 407187), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='End_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 19, 19, 52, 407187), null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 19, 19, 52, 407187), null=True),
        ),
    ]
