# Generated by Django 3.0.8 on 2022-05-21 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220521_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='End_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 30, 40, 939723), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Start_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 30, 40, 939723), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='End_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 30, 40, 939723), null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 30, 40, 939723), null=True),
        ),
    ]
