# Generated by Django 3.0.8 on 2022-05-21 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220521_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='Paid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='End_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 34, 35, 786491), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Start_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 34, 35, 786491), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='End_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 34, 35, 786491), null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 21, 21, 34, 35, 786491), null=True),
        ),
    ]
